sources:
  - name: statistics
    handler:
      graphql:
        endpoint: ${PUBLIC_STATISTICS_GRAPH_URL}

  - name: bets-memory
    handler:
      graphql:
        endpoint: ${PUBLIC_BETS_MEMORY_GRAPH_URL}
  - name: dynamic-staking
    handler:
      graphql:
        endpoint: ${PUBLIC_DYNAMIC_STAKING_GRAPH_URL}
    transforms:
      - rename:
          renames:
            - from:
                type: Query
                field: profitDistributions
              to:
                type: Query
                field: profitDistributionsDynamic
  - name: conservative-staking
    handler:
      graphql:
        endpoint: ${PUBLIC_CONSERVATIVE_STAKING_GRAPH_URL}
  - name: uniswap
    handler:
      graphql:
        endpoint: ${PUBLIC_UNISWAP_GRAPH_URL}

codegen:
  scalars:
    BigInt: bigInt
    Bytes: string

documents:
  - ./src/lib/schema.graphql
