/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TemplateImport } from './routes/template'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TemplateRoute = TemplateImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/template': {
      id: '/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/template': typeof TemplateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/template': typeof TemplateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/template': typeof TemplateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/template'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/template'
  id: '__root__' | '/' | '/template'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplateRoute: typeof TemplateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplateRoute: TemplateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/template"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/template": {
      "filePath": "template.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
